CREATE SEQUENCE person_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE Person (
    id NUMBER PRIMARY KEY,
    first_name VARCHAR2(255),
    last_name VARCHAR2(255)
);

CREATE OR REPLACE TRIGGER person_trigger
BEFORE INSERT ON Person
FOR EACH ROW
BEGIN
    SELECT person_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;








DROP TABLE  BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE  BATCH_JOB_EXECUTION_CONTEXT;
DROP TABLE  BATCH_STEP_EXECUTION;
DROP TABLE  BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE  BATCH_JOB_EXECUTION;
DROP TABLE  BATCH_JOB_INSTANCE;

DROP SEQUENCE  BATCH_STEP_EXECUTION_SEQ;
DROP SEQUENCE  BATCH_JOB_EXECUTION_SEQ;
DROP SEQUENCE  BATCH_JOB_SEQ;